pom.xml
src/main/java/com/dylabs/zuko/controller/GenreController.java
src/main/java/com/dylabs/zuko/dto/GenreRequest.java
src/main/java/com/dylabs/zuko/dto/request/GenreRequest.java
src/main/java/com/dylabs/zuko/dto/response/GenreResponse.java
src/main/java/com/dylabs/zuko/exception/GenreAlreadyExistsException.java
src/main/java/com/dylabs/zuko/exception/GenreNotFoundException.java
src/main/java/com/dylabs/zuko/exception/GlobalExceptionHandler.java
src/main/java/com/dylabs/zuko/mapper/GenreMapper.java
src/main/java/com/dylabs/zuko/model/Genre.java
src/main/java/com/dylabs/zuko/repository/GenreRepository.java
src/main/java/com/dylabs/zuko/service/GenreService.java
src/main/resources/application.properties

Este PR implementa la funcionalidad principal para gestionar géneros musicales en la aplicación, pendiente solo de ajustes por futuras integraciones. Se desarrolló:
- Conexión con base de datos PostgreSQL.
- Modelo Genre con anotaciones JPA.
- Repositorio `GenreRepository` con métodos personalizados.
- Servicio `GenreService` con lógica para registrar, listar, editar y eliminar géneros.
- DTOs de request y response con validaciones usando Jakarta Validation.
- `GenreMapper` para conversión entre entidades y DTOs.
- Manejo de excepciones con `GenreAlreadyExistsException`, `GenreNotFoundException` y un `GlobalExceptionHandler`.
- Controlador `GenreController` con endpoints RESTful (`POST`, `GET`, `PUT`, `DELETE`).
- Pruebas de endpoints realizadas exitosamente con Postman (casos válidos e …

Implementar endpoints y lógica para gestión de géneros musicales - [US-13][US-14][US-15]

---

src/main/java/com/dylabs/zuko/controller/UserController.java
src/main/java/com/dylabs/zuko/service/UserService.java

Se agregó un endpoint que permite obtener una lista completa de todos los usuarios del sistema.
Se implementó la conversión de cada usuario a su representación en el DTO (UserResponse) para ser devuelto como respuesta.
Se gestionaron los posibles errores, asegurando que la respuesta sea exitosa incluso si no hay usuarios registrados.
El sistema devuelve una respuesta con formato estándar (ApiResponse) confirmando que la operación se realizó exitosamente.

US 24 - Ver listado de usuarios

---

src/main/java/com/dylabs/zuko/controller/UserController.java
src/main/java/com/dylabs/zuko/dto/request/CreateUserRequest.java
src/main/java/com/dylabs/zuko/dto/response/UserResponse.java
src/main/java/com/dylabs/zuko/mapper/UserMapper.java
src/main/java/com/dylabs/zuko/model/User.java
src/main/java/com/dylabs/zuko/service/UserService.java

Se agregó un endpoint PATCH /users/{id}/toggle-active que permite cambiar el estado de actividad de un usuario de manera toggle (activar o desactivar).
Se gestionó la lógica para actualizar el campo isActive del usuario y guardar el cambio en la base de datos.
La respuesta del endpoint es una confirmación de que el estado del usuario fue actualizado correctamente.

US 25 - Cambiar estado de actividad de cuenta

---

src/main/java/com/dylabs/zuko/controller/UserController.java
src/main/java/com/dylabs/zuko/service/UserService.java

Se agregó el endpoint GET /users/{id}, que permite obtener la información completa de un usuario a partir de su ID.
Se incluyó la lógica para recuperar el usuario desde la base de datos, verificando si existe. En caso de que no se encuentre, se devuelve un error adecuado.
El perfil del usuario incluye los detalles como el nombre de usuario, correo electrónico, imagen de perfil, descripción, rol, y el estado de actividad.
La respuesta incluye un objeto con la información completa del usuario para su visualización.

US 17 - Mostrar perfil de usuario

---

src/main/java/com/dylabs/zuko/controller/UserController.java
src/main/java/com/dylabs/zuko/dto/ApiResponse.java
src/main/java/com/dylabs/zuko/dto/request/CreateRoleRequest.java
src/main/java/com/dylabs/zuko/dto/request/CreateUserRequest.java
src/main/java/com/dylabs/zuko/dto/request/UpdateUserRequest.java
src/main/java/com/dylabs/zuko/dto/response/UserResponse.java
src/main/java/com/dylabs/zuko/exception/GlobalExceptionHandler.java
src/main/java/com/dylabs/zuko/model/User.java
src/main/java/com/dylabs/zuko/service/UserService.java

Se agregó el endpoint PATCH /users/{id}, que permite actualizar los detalles del perfil de un usuario utilizando su ID.
La funcionalidad permite modificar campos específicos como nombre de usuario, correo electrónico, descripción, URL de imagen y contraseña.
Solo los campos enviados en la solicitud se actualizan, sin requerir que se envíen todos los campos.
Si algún campo no es enviado en la solicitud, se deja sin cambios en la base de datos.
Se validan los datos de entrada (como el formato del correo electrónico y la contraseña) antes de realizar la actualización.

US 18 - Edición de perfil de usuario

---

src/main/java/com/dylabs/zuko/controller/ArtistController.java
src/main/java/com/dylabs/zuko/dto/request/UpdateArtistRequest.java
src/main/java/com/dylabs/zuko/service/ArtistService.java

- Se agregó el endpoint PUT/api/v1/artists/{id} para actualizar los datos del artista.
- La funcionalidad permite modificar campos específicos como nombre de nombre, país y bibliografía.
- Si se cambia el nombre, este no debe estar en uso por otro artista.

US 08 - Editar perfil del artista

---

src/main/java/com/dylabs/zuko/controller/ArtistController.java
src/main/java/com/dylabs/zuko/dto/request/UpdateArtistRequest.java
src/main/java/com/dylabs/zuko/dto/response/ArtistResponse.java
src/main/java/com/dylabs/zuko/mapper/ArtistMapper.java
src/main/java/com/dylabs/zuko/model/Artist.java
src/main/java/com/dylabs/zuko/service/ArtistService.java

- Se agregó el endpoint PATCH/api/v1/artists/{id}/toggle-active para cambiar la actividad del artista.
- Se gestionó la lógica para actualizar el campo isActive del artista y guardar el cambio en la base de datos.
- La respuesta del endpoint es una confirmación de que el estado del artista fue actualizado correctamente.

US 26 - Cambiar estado de actividad del artista

---

src/main/java/com/dylabs/zuko/controller/AlbumController.java
src/main/java/com/dylabs/zuko/exception/GlobalExceptionHandler.java
src/main/java/com/dylabs/zuko/exception/albumExceptions/AlbumNotFoundException.java
src/main/java/com/dylabs/zuko/exception/albumExceptions/AlbumPermissionException.java
src/main/java/com/dylabs/zuko/exception/albumExceptions/AlbumValidationException.java
src/main/java/com/dylabs/zuko/repository/AlbumRepository.java
src/main/java/com/dylabs/zuko/service/AlbumService.java

Este PR implementa las siguientes mejoras y correcciones en la funcionalidad de álbumes:
Reemplazo de IllegalArgumentException por excepciones personalizadas:
- Se lanza AlbumPermissionException cuando un artista intenta editar o eliminar un álbum que no le pertenece.
- Se lanza AlbumValidationException cuando se intenta crear o actualizar un álbum con menos de dos canciones.
Centralización del manejo de errores:
- Se eliminó el manejo directo de excepciones en el controller.
- Se delega todo al GlobalExceptionHandler, siguiendo el estándar del equipo.
Validación de título único al editar álbumes:
- Se agregó una verificación para evitar duplicación de títulos entre álbumes del mismo artista.

Fix album exceptions 

---

src/main/java/com/dylabs/zuko/service/SongService.java
src/test/java/com/dylabs/zuko/service/SongServiceUnitTest.java

Este PR incorpora la implementación y documentación de pruebas unitarias para las funcionalidades de creación, edición y eliminación de canciones en el sistema. Las pruebas cubren tanto escenarios exitosos como condiciones de error, asegurando el cumplimiento de las reglas de negocio y los mensajes esperados para el usuario.
Además, se mejoró la gestión de excepciones con mensajes personalizados para casos como intentos de editar o eliminar canciones que no existen en el catálogo del artista, o con datos inválidos (como títulos demasiado cortos).
También se preparó la estructura para facilitar la validación futura de autenticación y roles (como ADMIN), necesaria para controlar la eliminación de canciones de forma segura.
Resultados de cobertura (SongService):
- Métodos: 100%
- Líneas: …

Pruebas unitarias para SongService

---

src/test/java/com/dylabs/zuko/service/ArtistServiceUnitTest.java

Pruebas unitarias para gestión de artistas (creación, edición, visualización y activación/desactivación)
Este Pull Request incluye la implementación y documentación de pruebas unitarias para las principales funcionalidades del módulo ArtistService, abarcando:
Creación de artista
Edición de datos del artista
Visualización del artista
Cambio de estado activo/inactivo del artista
Las pruebas consideran escenarios exitosos y errores previstos, validando reglas de negocio y asegurando una respuesta coherente al usuario final.
Funcionalidades cubiertas:
Creación de artista:
- Registro correcto de un nuevo artista. 
- Registro fallido por usuario que ya tiene un artista. 
- Registro fallido por nombre de artista duplicado. 
- Registro fallido por país vacío.
Edición de artista
- Edición correcta …

Feat:Completar el test del artista

---

src/main/java/com/dylabs/zuko/controller/SongController.java
src/main/java/com/dylabs/zuko/service/SongService.java
src/test/java/com/dylabs/zuko/service/SongServiceUnitTest.java

Se implementaron mejoras de seguridad y autorización en la clase Song para asegurar que solo usuarios con permisos adecuados (ADMIN o ARTIST autenticado) puedan crear, editar o eliminar canciones. Además, se actualizaron y añadieron pruebas unitarias para cubrir estos nuevos controles de acceso y garantizar la correcta funcionalidad del servicio.
Cambios principales:
Validaciones de roles y autorización en métodos de creación, actualización y eliminación.
Ajustes en el manejo de la relación entre usuarios ARTIST y sus canciones.
Pruebas unitarias ampliadas y adaptadas para cubrir todos los casos de permisos.
Resultados de cobertura:
Métodos: 100%
Líneas: 100%
Ramas: 100%
Las nuevas pruebas se ejecutaron correctamente de forma local y validan los comportamientos esperados del módulo.

Agregar seguridad y autorización en clase song con pruebas actualizadas

---

src/main/java/com/dylabs/zuko/service/PlaylistService.java
src/test/java/com/dylabs/zuko/service/PlaylistServiceUnitTest.java

- Se agregan y documentan tests unitarios para todos los métodos públicos del servicio PlaylistService.
- Los tests cubren escenarios positivos y negativos: creación, obtención, eliminación, listado de canciones, y operaciones de agregar/quitar canciones en playlists.
- Incluye pruebas de control de acceso para usuario owner, admin y restricciones para usuarios no autorizados.
- Se utilizan mocks de dependencias (repositorios, mappers) y se validan respuestas esperadas y excepciones custom.
- Los resultados esperados en cada test reflejan los códigos de estado HTTP y mensajes definidos para la API REST.
- Se logro una cobertura del 100% en métodos, 100% en lineas, y 87% en ramas. 
---
**Esta PR garantiza la robustez y el correcto funcionamiento de la lógica de negocio de PlaylistService, …

[test] Tests unitarios  para PlaylistService

---

README.md
docker-compose.dev.yml

Este pull request añade el archivo docker-compose.yml para despliegue y testing usando la imagen publicada en Docker Hub, mejorando la portabilidad y la facilidad de integración para el equipo.
- Agrega docker-compose.yml que utiliza la imagen turppie/zuko-backend:latest, permitiendo levantar backend y base de datos con un solo comando.
- Actualiza y documenta el README con pasos claros para levantar el entorno con Docker Compose, tanto para desarrollo como para producción.
- Mantiene el archivo docker-compose.dev.yml para facilitar el desarrollo local y pruebas en caliente.
Esto simplifica el onboarding de nuevos colaboradores y facilita despliegues en cualquier entorno.

feat: agregar docker-compose de producción y README con instrucciones de despliegue

---

src/main/java/com/dylabs/zuko/controller/AlbumController.java
src/main/java/com/dylabs/zuko/model/Album.java
src/main/java/com/dylabs/zuko/service/AlbumService.java
src/test/java/com/dylabs/zuko/service/AlbumServiceUnitTest.java

Este PR implementa y refuerza la validación de canciones asociadas a álbumes, asegurando la integridad de datos y la correcta gestión de relaciones entre entidades.
Incluye los siguientes cambios:
🔹 Controller: Se quitaron comentarios innecesarios para mantener la limpieza y orden del codigo.
🔹 Service: Se añadió validación en AlbumService para que solo se puedan asociar canciones existentes y pertenecientes al artista correspondiente al crear o actualizar un álbum.
🔹 Model: Se modificó la relación @OneToMany en la entidad Album para evitar la eliminación de canciones
🔹 Tests: Se agregaron tests unitarios negativos y de borde en AlbumServiceUnitTest para cubrir los nuevos caminos de validación (canción inexistente, canción de otro artista).
Resultados de cobertura (AlbumService):
Métodos: …

Feat: Arreglar manejo de canciones dentro del AlbumService

---

src/main/java/com/dylabs/zuko/controller/AlbumController.java
src/main/java/com/dylabs/zuko/repository/AlbumRepository.java
src/main/java/com/dylabs/zuko/service/AlbumService.java
src/test/java/com/dylabs/zuko/service/AlbumServiceUnitTest.java

Se agregaron funciones necesarias de busqueda por nombre del album para el uso en frontend:
- Busqueda de todos los albumes
- Busqueda de albumes para el propio ususario artista
- Busqueda de un album por nombre
Resultados de cobertura (AlbumService):
Métodos: 100%
Líneas: 100%
Ramas: 100%

Feat: Corregir manejo al buscar y obtener albums

---

src/main/java/com/dylabs/zuko/dto/request/AlbumRequest.java
src/main/java/com/dylabs/zuko/model/Album.java
src/main/java/com/dylabs/zuko/service/AlbumService.java
src/test/java/com/dylabs/zuko/service/AlbumServiceUnitTest.java

Se modifico la manera en la cual el álbum valida el artista, para permitir una mayor eficiencia y un manejo correcto tanto el Backend como en el Frontend.
Resultados de cobertura (AlbumService):
Métodos: 100%
Líneas: 100%
Ramas: 100%

Feat: Arreglar manejo al crear un Album

---

src/main/java/com/dylabs/zuko/controller/AlbumController.java
src/main/java/com/dylabs/zuko/controller/PlaylistController.java
src/main/java/com/dylabs/zuko/dto/request/UpdatePlaylistRequest.java
src/main/java/com/dylabs/zuko/repository/AlbumRepository.java
src/main/java/com/dylabs/zuko/service/AlbumService.java
src/main/java/com/dylabs/zuko/service/PlaylistService.java

Resumen
Se implementa un nuevo endpoint en el módulo de álbumes que permite obtener la información de un álbum dado el songId de una de sus canciones. Este endpoint facilita la consulta cruzada desde cualquier parte del frontend (por ejemplo, vista de playlist, detalles de canción, etc).
Cambios principales
Agregado método findAlbumBySongId en AlbumRepository (con JPQL join).
Agregado método getAlbumBySongId(Long songId) en AlbumService.
Nuevo endpoint GET /albums/from-song/{songId} en AlbumController.
Manejo de excepción si la canción no pertenece a ningún álbum.
Endpoint probado y funcional, retorna la info estructurada en el DTO AlbumResponse.
Motivación
Permite al frontend mostrar el álbum al que pertenece una canción incluso si el modelo Song no tiene relación directa con Album. …

Endpoint para obtener álbum a partir del ID de canción

---

src/main/java/com/dylabs/zuko/dto/request/SongRequest.java
src/main/java/com/dylabs/zuko/dto/response/SongResponse.java
src/main/java/com/dylabs/zuko/mapper/PlaylistMapper.java
src/main/java/com/dylabs/zuko/mapper/SongMapper.java
src/main/java/com/dylabs/zuko/model/Song.java
src/main/java/com/dylabs/zuko/service/SongService.java

Se añade soporte para registrar y actualizar canciones con enlaces de YouTube, lo que permite su posterior reproducción desde el frontend.
- Se agregó el campo `youtubeUrl` en:
- `SongRequest`
- `SongResponse`
- Entidad `Song`
- Se actualizó `SongMapper` para incluir el nuevo campo.
- Se modificó `SongService` para guardar y actualizar correctamente el campo `youtubeUrl`.
- Se realizaron pequeños ajustes en `PlaylistMapper` (formato).
-
1. Crear o editar una canción desde Postman enviando un campo `youtubeUrl`.
2. Verificar que se almacena correctamente en la base de datos.
3. Confirmar que el campo se devuelve en el `GET /songs`.
Este cambio es necesario para permitir la reproducción desde el frontend usando la API de YouTube.

feat(song): soporte para reproducción con enlace de YouTube

---

src/main/java/com/dylabs/zuko/controller/ShortcutsController.java
src/main/java/com/dylabs/zuko/dto/request/AddPlaylistToShortcutsRequest.java
src/main/java/com/dylabs/zuko/dto/response/PlaylistSummaryResponse.java
src/main/java/com/dylabs/zuko/dto/response/ShortcutsResponse.java
src/main/java/com/dylabs/zuko/exception/GlobalExceptionHandler.java
src/main/java/com/dylabs/zuko/exception/shortcutsExceptions/PlaylistAlreadyInShortcutsException.java
src/main/java/com/dylabs/zuko/mapper/ShortcutsMapper.java
src/main/java/com/dylabs/zuko/model/Shortcuts.java
src/main/java/com/dylabs/zuko/repository/ShortcutsRepository.java
src/main/java/com/dylabs/zuko/service/ShortcutsService.java
src/main/java/com/dylabs/zuko/service/UserService.java

- Este PR introduce la funcionalidad completa de shortcuts (accesos directos) para playlists, permitiendo a los usuarios guardar playlists favoritas para acceso rápido.
Incluye todo el flujo backend: modelo, DTOs, mapper, repositorio, service, controller y validación de duplicados.
- Creación del modelo Shortcuts con relaciones many-to-many a playlists y álbumes.
- Implementación de DTOs resumidos: PlaylistSummaryResponse y ShortcutsResponse.
- Mapper para transformar entidades a respuestas optimizadas para frontend.
- Repositorio, service y controller para CRUD y gestión de shortcuts.
- Validación para evitar añadir dos veces la misma playlist a los shortcuts de un usuario, con excepción custom y manejo de error adecuado.
- Nota: Los usuarios existentes en la base de datos no tendrán …

feat: implementación de shortcuts (accesos directos) para playlists con validación y manejo de duplicados

---

src/main/java/com/dylabs/zuko/model/Shortcuts.java

Este PR habilita el borrado en cascada (ON DELETE CASCADE) de playlists en la relación many-to-many con shortcuts. De ahora en adelante, al eliminar una playlist, se eliminan automáticamente todas las referencias asociadas en la tabla Intermedia, evitando errores de integridad referencial y simplificando la gestión de datos relacionados.
- Facilita la limpieza automática de accesos directos al eliminar playlists.

fix: habilitar borrado en cascada de playlists referenciadas en shortcuts

---

src/main/java/com/dylabs/zuko/dto/response/AlbumResponse.java
src/main/java/com/dylabs/zuko/mapper/AlbumMapper.java
src/main/java/com/dylabs/zuko/mapper/ShortcutsMapper.java

Este cambio permite que el Álbum obtenga el Genero Id, permitiendo la visualización del mismo al momento de editar un Álbum.

Fix/AlbumUpdateB Feat: Añadir ID de genero en el Album Response

---

src/main/java/com/dylabs/zuko/repository/AlbumRepository.java
src/main/java/com/dylabs/zuko/service/AlbumService.java

Se arreglo el manejo de álbumes en nuevos lanzamientos, ahora en ves de mostrarse los últimos 3 lanzamientos de álbumes del día, son los 3 últimos creados de la base de datos.

Feat: Arreglar ultimos 3 albumes de la DB
